### Formular: y = 5x-10

- target: y = 10 find x. Expected x = 4
- loss function: 
$$
z = \frac{1}{2}(y - y_{\text{target}})^2
$$
- dz/dy = y-y_target
$$
\frac{\partial z}{\partial y} = y - y_{\text{target}}
$$
- dy/dx = 5
$$
\frac{\partial y}{\partial x} = 5
$$
- dz/dx = dz/dy * dy/dx= (y-y_target)*5
$$
\frac{\partial z}{\partial x} = \frac{\partial z}{\partial y} \cdot \frac{\partial y}{\partial x} = (y - y_{\text{target}}) \cdot 5
$$

- update x: x = x - learning_rate * dz/dx
$$
x = x - \eta \cdot \frac{\partial z}{\partial x}
$$

In [1]:
x = 0
y_target = 10
learning_rate = 1e-3 
def loss(y,y_target):
    return 1/2*(y-y_target)**2
for i in range(1000):
    y = 5*x-10
    x = x - learning_rate * (y-y_target)*5
    y = 5*x-10
    if abs(loss(y,y_target))<1e-6:
        break
print(f'x: {x}',f'y: {y}')

x: 3.999720871150599 y: 9.998604355752995


### Forward pass:

Given:

$$
X = \begin{bmatrix}
x_1 & x_2 \\
x_3 & x_4
\end{bmatrix}, \quad
W = \begin{bmatrix}
w_1 & w_2 \\
w_3 & w_4
\end{bmatrix}

$$

Output:

$$
y = \begin{bmatrix}
y_1 & y_2
\end{bmatrix}, \quad
y_{\text{target}} = \begin{bmatrix}
y_1' & y_2'
\end{bmatrix}

$$

With:

$$
y_1 = x_1 w_1 + x_2 w_3 \\
y_2 = x_1 w_2 + x_2 w_4

$$

---

### Loss function:

$$
\mathcal{L} = \frac{1}{2} (y - y_{\text{target}})^2

$$

---

### Gradient of the loss w.r.t. output:

$$
\frac{\partial \mathcal{L}}{\partial y_1} = y_1 - y_1' \\
\frac{\partial \mathcal{L}}{\partial y_2} = y_2 - y_2'

$$

---

### Derivatives of output w.r.t. weights:

From:

$$
y_1 = x_1 w_1 + x_2 w_3 \Rightarrow
\frac{\partial y_1}{\partial w_1} = x_1, \quad
\frac{\partial y_1}{\partial w_3} = x_2

$$

$$
y_2 = x_1 w_2 + x_2 w_4 \Rightarrow
\frac{\partial y_2}{\partial w_2} = x_1, \quad
\frac{\partial y_2}{\partial w_4} = x_2

$$

---

### Gradient of the loss w.r.t. weights:

$$
\frac{\partial \mathcal{L}}{\partial W} = X^\top \cdot \frac{\partial \mathcal{L}}{\partial y}

$$

Dimensions:

So:

$$
\frac{\partial \mathcal{L}}{\partial W} \in \mathbb{R}^{2 \times 2}

$$

---

### Multiple samples (batch training):

If we train on multiple samples:

$$
\frac{\partial \mathcal{L}}{\partial w_1} =
\sum_{i=1}^n \left( \frac{\partial \mathcal{L}^{(i)}}{\partial y_1^{(i)}} \cdot \frac{\partial y_1^{(i)}}{\partial w_1} \right)

$$

Which generalizes to:

$$
\frac{\partial \mathcal{L}}{\partial W} = X^\top \cdot \frac{\partial \mathcal{L}}{\partial y}

$$

---

### Weight update rule:

$$
W = W - \eta \cdot \frac{\partial \mathcal{L}}{\partial W}

$$

Where $\eta$  is the **learning rate**.


In [27]:
import numpy as np

In [31]:
arr = np.array([
    [-5,6,-5,2],
    [1,2,9,-5],
    [-5,-0.5,-5,2],
    [-5,6,-5,2],
])

In [32]:

np.maximum(2,arr)

array([[2., 6., 2., 2.],
       [2., 2., 9., 2.],
       [2., 2., 2., 2.],
       [2., 6., 2., 2.]])

In [33]:
np.where(arr>0,1,0)

array([[0, 1, 0, 1],
       [1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1]])

In [40]:
2.718**6

403.1778962208906

In [61]:
np.sum([[1,2,3],[1,2,4]],axis=-1,keepdims=True)

array([[6],
       [7]])

In [60]:
np.max(arr, axis=-1, keepdims=True),np.max(arr, axis=-1)

(array([[6.],
        [9.],
        [2.],
        [6.]]),
 array([6., 9., 2., 6.]))

In [68]:
np.exp(arr),np.sum(np.exp(arr),axis=-1,keepdims=True)

(array([[6.73794700e-03, 4.03428793e+02, 6.73794700e-03, 7.38905610e+00],
        [2.71828183e+00, 7.38905610e+00, 8.10308393e+03, 6.73794700e-03],
        [6.73794700e-03, 6.06530660e-01, 6.73794700e-03, 7.38905610e+00],
        [6.73794700e-03, 4.03428793e+02, 6.73794700e-03, 7.38905610e+00]]),
 array([[4.10831325e+02],
        [8.11319800e+03],
        [8.00906265e+00],
        [4.10831325e+02]]))

In [67]:
np.exp(arr)/np.sum(np.exp(arr),axis=-1,keepdims=True)

array([[1.64007625e-05, 9.81981578e-01, 1.64007625e-05, 1.79856200e-02],
       [3.35044433e-04, 9.10745195e-04, 9.98753380e-01, 8.30492119e-07],
       [8.41290335e-04, 7.57305425e-02, 8.41290335e-04, 9.22586877e-01],
       [1.64007625e-05, 9.81981578e-01, 1.64007625e-05, 1.79856200e-02]])

In [99]:
def softmax_derivative_from_output_2d(softmax_output):
    """
    Calculate Jacobian of Softmax for each column in batch.

    softmax_output: numpy array (shape: [num_classes, batch_size])
    Output: numpy array (shape: [batch_size, num_classes, num_classes])
    """

    num_classes, batch_size = softmax_output.shape
    jacobian_matrices = np.zeros((batch_size, num_classes, num_classes))

    for i in range(batch_size): 
        s = softmax_output[:, i].reshape(-1, 1) 
        jacobian_matrices[i] = np.diagflat(s) - np.dot(s, s.T)

    return jacobian_matrices
softmax_derivative_from_output_2d(np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3],
])).shape

(3, 3, 3)

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist

class Dense:
    @staticmethod
    def linear(Z):
        return Z

    @staticmethod
    def linear_derivative(Z):
        return np.ones_like(Z)
    
    @staticmethod
    def relu(Z):
        return np.maximum(0, Z)

    @staticmethod
    def relu_derivative(Z):
        return np.where(Z > 0, 1, 0)
    
    @staticmethod
    def leaky_relu(Z, alpha=0.01):
        return np.where(Z > 0, Z, alpha * Z)

    @staticmethod
    def leaky_relu_derivative(Z, alpha=0.01):
        return np.where(Z > 0, 1, alpha)
    
    @staticmethod
    def softmax(Z):
        expZ = np.exp(Z - np.max(Z, axis=1, keepdims=True)) 
        return expZ / np.sum(expZ, axis=1, keepdims=True)
    
    @staticmethod
    def softmax_derivative(s): 
        """
        s: shape=(num_class)
        """
        s = s.reshape(-1, 1)  # convert to vector column
        return np.diagflat(s) - np.dot(s, s.T)  # Jacobian matrix
    
    @staticmethod
    def softmax_derivative_from_output_2d(softmax_output):
        """
        Calculate Jacobian of Softmax for each sample in batch.
        
        softmax_output: numpy array (shape: [batch_size, num_classes])
        Output: numpy array (shape: [batch_size, num_classes, num_classes])
        """
        batch_size, num_classes = softmax_output.shape
        jacobian_matrices = np.zeros((batch_size, num_classes, num_classes))

        for i in range(batch_size): 
            s = softmax_output[i, :].reshape(-1, 1) 
            jacobian_matrices[i] = np.diagflat(s) - np.dot(s, s.T)

        return jacobian_matrices
    
    def __init__(self, output_size, activation='relu', learning_rate=1e-4):
        self.output_size = output_size
        self.learning_rate = learning_rate
        self.is_output = False
        self.weight = None
        self.bias = None
        
        if activation == 'relu':
            self.activation = self.relu
            self.backward_activation = self.relu_derivative
        elif activation == 'leaky_relu':
            self.activation = self.leaky_relu
            self.backward_activation = self.leaky_relu_derivative
        elif activation == 'softmax':
            self.activation = self.softmax
            self.backward_activation = self.softmax_derivative_from_output_2d
        else:
            self.activation = self.linear
            self.backward_activation = self.linear_derivative

    def get_input_size(self):
        return self.input_size
    
    def get_output_size(self):
        return self.output_size

    def init_weight(self, input_size):
        self.input_size = input_size
        # Xavier initialization
        self.weight = np.random.randn(input_size, self.output_size) * np.sqrt(2/input_size)
        self.bias = np.zeros((1, self.output_size))

    def forward(self, inputs):
        # inputs.shape = (batch_size, input_size)
        # weight.shape = (input_size, output_size)
        
        if self.weight is None:
            self.init_weight(inputs.shape[1])
        
        # Z.shape = (batch_size, output_size)
        Z = inputs @ self.weight + self.bias
        
        # A.shape = (batch_size, output_size)
        A = self.activation(Z)
        
        # saving for backward
        self.inputs = inputs 
        self.Z = Z
        self.A = A
        
        return A
    # dl/da da/dz dl/dz * dz/dw  z = x@w
    def backward(self, dl_da):
        # dl_da.shape = (batch_size, output_size)
        batch_size = dl_da.shape[0]
        
        if self.activation == self.softmax:
            # For softmax, we need to handle the Jacobian properly
            da_dz = self.backward_activation(self.A)  # (batch_size, output_size, output_size)
            dl_dz = np.zeros_like(dl_da)  # (batch_size, output_size)
            
            for i in range(batch_size):
                dl_dz[i, :] = da_dz[i] @ dl_da[i, :]
        else:
            # For other activations
            dl_dz = dl_da * self.backward_activation(self.Z)  # (batch_size, output_size)

        # Calculate gradients
        dl_dw = self.inputs.T @ dl_dz  # (input_size, output_size)
        dl_db = np.sum(dl_dz, axis=0, keepdims=True)  # (1, output_size)
        
        # Update weights and bias
        self.weight = self.weight - self.learning_rate * dl_dw
        self.bias = self.bias - self.learning_rate * dl_db
        
        # Calculate gradient for previous layer
        pre_dl_da = dl_dz @ self.weight.T  # (batch_size, input_size) because dl2 = da1 @ weight => dl2/da  =weight.T
        
        return pre_dl_da

class Sequential:
    def __init__(self, layers: list):
        self.layers: list = layers
        self.layers[-1].is_output = True
    
    @staticmethod
    def cross_entropy_derivative(y_true, y_pred):
        epsilon = 1e-9  # Small value to prevent division by zero
        return - (y_true / (y_pred + epsilon)) / y_true.shape[0]
    
    def fit(self, data, label, batch_size=10, epochs=2, learning_rate=None):
        if learning_rate is not None:
            for layer in self.layers:
                layer.learning_rate = learning_rate
                
        for epoch in range(epochs):
            total_loss = 0
            num_batches = 0
            
            for i in range(0, data.shape[0], batch_size):
                data_batch = data[i:i+batch_size, :]      # shape: (batch_size, 784)
                label_batch = label[i:i+batch_size, :]    # shape: (batch_size, 10)
                
                # Forward pass
                A = data_batch
                for layer in self.layers:
                    A = layer.forward(A)

                # Calculate loss
                A_clipped = np.clip(A, 1e-9, 1.0) 
                loss = -np.sum(label_batch * np.log(A_clipped)) / label_batch.shape[0]
                total_loss += loss
                num_batches += 1
                
                # Backward pass
                dl_da = self.cross_entropy_derivative(label_batch, A)
                for layer in reversed(self.layers):
                    dl_da = layer.backward(dl_da)

            avg_loss = total_loss / num_batches
            print(f'========epoch: {epoch+1}||loss: {avg_loss:.4f}======================')
                
    def predict(self, test_data):
        A = test_data
        for layer in self.layers:
            A = layer.forward(A)

        return np.argmax(A, axis=1)  

if __name__ == '__main__':
    (X_train, y_train), (X_test, y_test) = mnist.load_data()

    X_train = X_train.reshape(-1, np.prod(X_train.shape[1:])) / 255.0  # Normalize, shape (60000, 784)
    X_test = X_test.reshape(-1, np.prod(X_test.shape[1:])) / 255.0    # Normalize, shape (10000, 784)
    y_train = np.squeeze(y_train)
    y_test = np.squeeze(y_test)
    
    Y_train_one_hot = np.eye(10)[y_train]  # Shape (60000, 10)
    Y_test_one_hot = np.eye(10)[y_test]    # Shape (10000, 10)

    hidden_size = 256
    output_size = 10
    batch_size = 64
    epochs = 10
    learning_rate = 1e-3

    model = Sequential([
        Dense(hidden_size, activation='relu'),
        Dense(256, activation='relu'),
        Dense(output_size, activation='softmax') 
    ])
    
    model.fit(X_train, Y_train_one_hot, batch_size=batch_size, epochs=epochs, learning_rate=learning_rate)
    predictions = model.predict(X_test)
    
    # Calculate accuracy
    accuracy = np.mean(predictions == y_test)
    print(f'Accuracy: {accuracy:.4f}')
    print(f'Predictions shape: {predictions.shape}')

========epoch: 1||loss: 0.7233======================
========epoch: 2||loss: 0.3278======================
========epoch: 3||loss: 0.2727======================
========epoch: 4||loss: 0.2401======================
========epoch: 5||loss: 0.2166======================
========epoch: 6||loss: 0.1982======================
========epoch: 7||loss: 0.1831======================
========epoch: 8||loss: 0.1704======================
========epoch: 9||loss: 0.1594======================
========epoch: 10||loss: 0.1497======================
Accuracy: 0.9546
Predictions shape: (10000,)


In [3]:
for i in range(100,200):
    print(predictions[i],y_test[i])

6 6
0 0
5 5
4 4
9 9
9 9
2 2
1 1
9 9
4 4
8 8
7 7
3 3
9 9
7 7
4 4
4 4
4 4
9 9
2 2
5 5
4 4
7 7
6 6
4 7
9 9
0 0
5 5
8 8
5 5
6 6
6 6
5 5
7 7
8 8
1 1
0 0
1 1
6 6
4 4
6 6
7 7
3 3
1 1
7 7
1 1
8 8
2 2
0 0
9 2
9 9
9 9
5 5
5 5
1 1
5 5
6 6
0 0
3 3
4 4
4 4
6 6
5 5
4 4
6 6
5 5
4 4
5 5
1 1
4 4
4 4
7 7
2 2
3 3
2 2
7 7
1 1
8 8
1 1
8 8
1 1
8 8
5 5
0 0
8 8
9 9
2 2
5 5
0 0
1 1
1 1
1 1
0 0
3 9
0 0
3 3
1 1
6 6
4 4
2 2


y= ax + b
dy/dx = a
z1 = x@w1 + b

dz1/dw1 = x.T

[1,2,3,5.7,8,9,2,0,1,5,5,2] index 10
[xin chào xin chào] = [3,5,3,5]
embeding = [
    [0.1,0.2,0.3] 1
    [0.1,0.2,0.3] 2
    [0.1,0.2,0.3] 3
    [0.1,0.2,0.3] 4
    [0.1,0.2,0.3] 5
    [0.1,0.2,0.3] 6
    [0.1,0.2,0.3] 7
    [0.1,0.2,0.3] 8 
    [0.1,0.2,0.3] 9
    [0.1,0.2,0.3] 10
]

embeding = x = 
[ 
    [0.1,0.2,0.3]
    [0.1,0.2,0.3]
    [0.1,0.2,0.3]
    [0.1,0.2,0.3]
]

y

x

w1

z1 = x@w1 + b

dl/dz1

dz1/dx

dz1/dx = w1.T

dl/dx = dl/dz1 * dz1/dx 

a1 = activation(z1)

w2

z2 = a1@w2 + b

a2 = activation(z2)

loss = l(a2,y) = 1/2(a2-y)^2

d1= dl/a2
d2 = da2/dz2
d3 = dz2/dw2

dl/dw2 = d1*d2*d3

w2 = w2 - leaning_rate*dl/dw2